config/routes.rb
Zoo::Application.routes.draw do
  get "purchases/index"

  get "sales/index"

  resources :owners, :only=> [:create, :destroy]
  match "purchases", :to => "purchases#index"
  match "sales", :to => "sales#index"

  resources :relationships
  resources :animals
  devise_for :users   
  resources :users
  resources :owners, :only => [:create, :destroy]


  root :to => "pages#home"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :predator, :class_name => "Animal"
  belongs_to :prey, :class_name => "Animal"

  validates :predator_id, :presence => true
  validates :prey_id,     :presence => true
end

# == Schema Information
#
# Table name: relationships
#
#  id          :integer         not null, primary key
#  predator_id :integer
#  prey_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :admin_user

  # GET /relationships
  # GET /relationships.xml

  def show
    redirect_to relationships_path
  end
  def index
    @relationships = Relationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @relationships }
    end
  end

  # GET /relationships/new
  # GET /relationships/new.xml
  def new
    @relationship = Relationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @relationship }
    end
  end

  # GET /relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /relationships
  # POST /relationships.xml
  def create
    @relationship = Relationship.new(params[:relationship])

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to(relationships_path, :notice => 'Relationship was successfully created.') }
        format.xml  { render :xml => relationships_path, :status => :created, :location => @relationship }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @relationship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /relationships/1
  # PUT /relationships/1.xml
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to(relationships_path, :notice => 'Relationship was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @relationship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.xml
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to(relationships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
     <%=render :partial => 'share/error_messages', :locals => {:record => @relationship}%>
  <div class="field">
    <%= f.collection_select :predator_id, Animal.all, :id, :species%>
    preys on

    <%= f.collection_select :prey_id, Animal.all, :id, :species%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h2>Editing relationship</h2>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<h2>Listing relationships</h2>

<table>
  <tr>
    <th>Predator</th>
    <th></th><th>Prey</th>
    <th></th>
    <th></th>

  </tr>

<% @relationships.each do |relationship| %>
  <tr>
    <td><%= link_to relationship.predator.species, animal_path(relationship.predator_id)%></td>
    <td> preys on </td>
    <td><%= link_to relationship.prey.species, animal_path(relationship.prey_id) %></td>
    <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
    <td><%= link_to 'Destroy', relationship, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h2>New relationship</h2>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>