config/routes.rb
Zoo::Application.routes.draw do
  get "purchases/index"

  get "sales/index"

  resources :owners, :only=> [:create, :destroy]
  match "purchases", :to => "purchases#index"
  match "sales", :to => "sales#index"

  resources :relationships
  resources :animals
  devise_for :users   
  resources :users
  resources :owners, :only => [:create, :destroy]


  root :to => "pages#home"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :users, :through => :owner
  has_many :relationships,          :foreign_key => "predator_id", :dependent => :destroy
  has_many :prey, :through => :relationships, :source => "prey"
  has_many :reverse_relationships,  :foreign_key => "prey_id", :dependent => :destroy,
                                    :class_name => "Relationship"
  has_many :predators, :through => :reverse_relationships, :source => "predator"
  has_many :sales
  has_many :purchases
  has_many :owners
  has_many :users, :through => :owners
  before_save :cap
  
  validates :species, :presence => true
  validates :info,    :presence => true
  validates :price,   :numericality => {:greater_than => 0}

  composed_of :price,
              :class_name => 'Money',
              :mapping => %w(price cents),
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : Money.empty }

  private
  def cap
    self.species.capitalize!
    self.info.capitalize!
  end


end


# == Schema Information
#
# Table name: animals
#
#  id         :integer         not null, primary key
#  species    :string(255)
#  info       :text
#  created_at :datetime
#  updated_at :datetime
#  price      :integer
#

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
before_filter :authenticate_user!, :except => [:show, :index]
before_filter :admin_user, :only => [:destroy, :edit, :create, :new, :update  ]

  # GET /animals
  # GET /animals.xml
  def index
    @animals = Animal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @animals }
    end
  end

  # GET /animals/1
  # GET /animals/1.xml
  def show
    @animal = Animal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @animal }
    end
  end

  # GET /animals/new
  # GET /animals/new.xml
  def new
    @animal = Animal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @animal }
    end
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
  end

  # POST /animals
  # POST /animals.xml
  def create
    @animal = Animal.new(params[:animal])

    respond_to do |format|
      if @animal.save
        format.html { redirect_to(animals_path, :notice => 'Animal was successfully created.') }
        format.xml  { render :xml => @animal, :status => :created, :location => @animal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @animal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /animals/1
  # PUT /animals/1.xml
  def update
    @animal = Animal.find(params[:id])

    respond_to do |format|
      if @animal.update_attributes(params[:animal])
        format.html { redirect_to(@animal, :notice => 'Animal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @animal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.xml
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to(animals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
    <%=render :partial => 'share/error_messages', :locals => {:record => @animal}%>


  <div class="field">
    <%= f.label :species %><br />
    <%= f.text_field :species %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h2>Editing animal</h2>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<h2>Listing animals</h2>

<table>
  <tr>
    <th>Species</th>
    <th>Price</th>
    <th>Info</th>
    <th></th>

      <%if current_user && current_user.admin?%>
    <th>Admin</th>
        <th>Actions</th>
        <%end%>
  </tr>

<% @animals.each do |animal| %>
  <tr>
    <td><%= link_to animal.species, animal %></td>
    <td>$<%= animal.price %></td>
    <td><%= animal.info %></td>
    <td>
      <%= form_for current_user.owners.build(:animal_id => animal.id) do |f| %>
  <div><%= f.hidden_field :animal_id %></div>
  <div class="actions"><%= f.submit "Buy" %></div>
<% end %>
      </td>

    <%if current_user.admin?%>
    <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
    <td><%= link_to 'Destroy', animal, :confirm => 'Are you sure?', :method => :delete %></td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

<%if current_user && current_user.admin?%>
		<%= link_to 'New Animal', new_animal_path %>
<%end%>

app/views/animals/new.html.erb
<h2>New animal</h2>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<h2>Showing Animal</h2>

<p>
  <b>Species:</b>
  <%= @animal.species %>
</p>
<p>
  <b>Info:</b>
  <%= @animal.info %>
</p>
<p>
  <b>Price:</b>
  $<%= @animal.price %>
</p>

<p>
<b>Predators:</b>
  <% @animal.predators.each do |predator|%>
      <%= predator.species%>,
  <%end%>
</p>

<p>
<b>Prey:</b>
  <% @animal.prey.each do|prey| %>
  <%= prey.species%>, <%end%>

</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>