config/routes.rb
Zoo::Application.routes.draw do
  get "purchases/index"

  get "sales/index"

  resources :owners, :only=> [:create, :destroy]
  match "purchases", :to => "purchases#index"
  match "sales", :to => "sales#index"

  resources :relationships
  resources :animals
  devise_for :users   
  resources :users
  resources :owners, :only => [:create, :destroy]


  root :to => "pages#home"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_adminbar.html.erb
<h4><span>Administrator's Bar</span></h4>
<ul class="blocklist">
	<li>
		<%= link_to "Edit Users", users_path%>
	</li>
	<li>
		<%= link_to "Edit Animals", animals_path%>
	</li>
	<li>
		<%= link_to "Manage Relationships", relationships_path%>
	</li>
    <li>
        <%= link_to "View Purchases", "/purchases" %>
    </li>
  <li>
        <%= link_to "View Sales", "/sales" %>
    </li>

</ul>

app/views/layouts/_defaultbar.html.erb
<h4><span>You are not logged in</span></h4>
<ul class="blocklist">
	<li>
		<%= link_to "Sign up", new_user_registration_path%>
	</li>
	<li>
		<%= link_to "Sign in", user_session_path%>
	</li>
	<li>
		<%= link_to "Explore the different animals", animals_path%>
	</li>
</ul>

app/views/layouts/_footer.html.erb
 <div id="footer">
          <div class="footer-content">
            <div class="footer-box">
                <h4>About the Zoo</h4>

                <p>
                    The Zoo is the implementation of the imagination of a 3 year old.  When asked for a fun idea for a website, his answer was, "I want a howler monkey and a puma.  I want to make him do tricks.  The rest is history.</p>
            </div>
            <div class="clear"></div>
        </div>
        <div id="footer-links">
        <!-- A link to http://www.spyka.net must remain. To remove link see http://www.spyka.net/licensing -->
                <p>&copy; TheZoo 2010. Design based on the work of <a href="http://www.spyka.net">Spyka.net</a></p>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	<%= render "layouts/userlogin"%> <h1><a href="/">The Zoo</a></h1>
	<h2>keep, collect, and trade exotic animals</h2>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
	<ul>
		<li>
			<%if user_signed_in?%>
				<%if current_user.admin?%>
					<%= render "layouts/adminbar"%>
					<%= render "layouts/userbar"%>
				<%else%>
					<%= render "layouts/userbar"%>
				<%end%>
				<h4><span>Your bank account</h4>
				<ul class="blocklist">
				<li>
					<p>$<%= current_user.money %></p>
				</li>
			</ul>
			<%else%>
			<%= render "layouts/defaultbar"%>
			<%end%>
		</li>
	</ul>
	<div class="sidebar-end"></div>
</div>

app/views/layouts/_userbar.html.erb
<h4><span><%= current_user.name%>'s Navigation</span></h4>
<ul class="blocklist">
                        <li><%= link_to  "Buy Animals", animals_path%></li>
                        <li><%= link_to "See your Zoo", user_path(current_user)%></li>
                        <li><%= link_to "See All Zoos", users_path%></li>
</ul>

app/views/layouts/_userlogin.html.erb
<div id = "userlogin">
<%if user_signed_in?%>
<p>You are logged in as <%=link_to current_user.name, user_path(current_user)%> <%=link_to "(edit account)", edit_user_registration_path%>, <%= link_to "Log out", destroy_user_session_path, :method => :delete%></p>
<%else%>
<p>You are not logged in, <%=link_to "Sign in", user_session_path%>, or <%=link_to "Sign up!", new_user_registration_path%></p>

      <%end%>
</div>

<%if notice%>
        	<div class="flash">
        	<p class="notice"><%= notice %></p>
        	</div>
        <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zoo</title>
  <%= stylesheet_link_tag "reset", "styles", "forms" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="wrapper">
    <div id="container">
        <%= render "layouts/header"%>
        
        <%= render "layouts/sidebar"%>
        <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        <%- end -%>
        <div id="body">
        	<div id="content">
        <%= yield %>
        </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
    <%=render "layouts/footer"%>
                     <%= debug(params) if Rails.env.development? %>
</body>
</html>